---
name: basic_banking
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_native_splash: ^2.2.17
  sqflite: ^2.2.4+1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  meta: ^1.8.0
  path_provider: ^2.0.12
  path: ^1.8.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/
flutter_native_splash:
  image: assets/splash.png
  color: '#ffffff'
  android_12:
    image: assets/splash.png
    color: '#ffffff'
